-- FreeGPT — full Supabase schema (multi-user, RLS-scoped).
-- Run once in: Supabase Dashboard -> SQL Editor -> New query -> paste -> Run.
--
-- Every table is owned by auth.uid(): the user_id column DEFAULTS to the caller's
-- id and Row Level Security only ever exposes a user their own rows. The frontend
-- never has to send user_id — the database stamps and filters it. This is what makes
-- the public app safe: one user can never read or write another user's data.

create extension if not exists vector;

-- ───────────────────────── Conversations ─────────────────────────
-- client_id is the id minted in the browser (localStorage). It is only unique
-- per user, so the real primary key is the surrogate `id` and we upsert on
-- (user_id, client_id).
create table if not exists conversations (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  client_id text not null,
  title text not null default 'New chat',
  messages jsonb not null default '[]'::jsonb,
  created_at bigint not null default 0,
  updated_at bigint not null default 0,
  unique (user_id, client_id)
);
create index if not exists conversations_user_idx on conversations (user_id, updated_at desc);

alter table conversations enable row level security;
create policy "own_conversations" on conversations
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ───────────────────────── Memories (pgvector) ─────────────────────────
create table if not exists memories (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  text text not null,
  summary text default '',
  embedding vector(384),
  category text default 'general',
  source text default 'chat',
  created_at bigint not null default 0,
  updated_at bigint not null default 0
);
create index if not exists memories_embedding_idx
  on memories using hnsw (embedding vector_cosine_ops);
create index if not exists memories_user_idx on memories (user_id);

alter table memories enable row level security;
create policy "own_memories" on memories
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Nearest memories by cosine distance, scoped to the caller. SECURITY INVOKER
-- (the default) means RLS still applies, but we also filter on user_id explicitly
-- so the ANN ordering never even considers other users' rows.
create or replace function match_memories(query_embedding vector(384), match_count int default 15)
returns table (id bigint, text text, summary text, category text, source text, created_at bigint, distance float)
language sql stable as $$
  select m.id, m.text, m.summary, m.category, m.source, m.created_at,
         (m.embedding <=> query_embedding) as distance
  from memories m
  where m.embedding is not null
    and m.user_id = auth.uid()
  order by m.embedding <=> query_embedding
  limit match_count;
$$;

-- ───────────────────────── Per-user settings ─────────────────────────
create table if not exists user_settings (
  user_id uuid primary key default auth.uid() references auth.users (id) on delete cascade,
  about_you text default '',
  custom_instructions text default '',
  memory_enabled boolean default true,
  updated_at bigint default 0
);

alter table user_settings enable row level security;
create policy "own_settings" on user_settings
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ───────────────────────── Shared chat snapshots ─────────────────────────
-- The slug `id` is an unguessable access token. Reads are PUBLIC (anyone with the
-- link, signed in or not) but only the owner can create or revoke a share.
create table if not exists shared_chats (
  id text primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  title text default 'Shared chat',
  messages jsonb not null default '[]'::jsonb,
  created_at bigint not null default 0
);

alter table shared_chats enable row level security;
create policy "public_read_shared" on shared_chats for select using (true);
create policy "owner_insert_shared" on shared_chats for insert with check (auth.uid() = user_id);
create policy "owner_delete_shared" on shared_chats for delete using (auth.uid() = user_id);

-- ───────────────────────── Subscriptions (Phase 2 — Stripe) ─────────────────────────
-- Placeholder for the $5/mo Pro tier. Written by the Stripe webhook (service role),
-- read by the user to know their plan. `plan` is 'free' | 'pro'.
create table if not exists subscriptions (
  user_id uuid primary key references auth.users (id) on delete cascade,
  plan text not null default 'free',
  status text default 'inactive',
  stripe_customer_id text,
  current_period_end bigint,
  updated_at bigint default 0
);

alter table subscriptions enable row level security;
create policy "own_subscription_read" on subscriptions for select using (auth.uid() = user_id);
