-- Vessa — full Supabase schema (multi-user, RLS-scoped).
-- Run once in: Supabase Dashboard -> SQL Editor -> New query -> paste -> Run.
--
-- Every table is owned by auth.uid(): the user_id column DEFAULTS to the caller's
-- id and Row Level Security only ever exposes a user their own rows. The frontend
-- never has to send user_id — the database stamps and filters it. This is what makes
-- the public app safe: one user can never read or write another user's data.

create extension if not exists vector;

-- ───────────────────────── Conversations ─────────────────────────
-- client_id is the id minted in the browser (localStorage). It is only unique
-- per user, so the real primary key is the surrogate `id` and we upsert on
-- (user_id, client_id).
create table if not exists conversations (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  client_id text not null,
  title text not null default 'New chat',
  messages jsonb not null default '[]'::jsonb,
  created_at bigint not null default 0,
  updated_at bigint not null default 0,
  unique (user_id, client_id)
);
create index if not exists conversations_user_idx on conversations (user_id, updated_at desc);

alter table conversations enable row level security;
create policy "own_conversations" on conversations
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ───────────────────────── Memories (pgvector) ─────────────────────────
create table if not exists memories (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  text text not null,
  summary text default '',
  embedding vector(384),
  category text default 'general',
  source text default 'chat',
  created_at bigint not null default 0,
  updated_at bigint not null default 0
);
create index if not exists memories_embedding_idx
  on memories using hnsw (embedding vector_cosine_ops);
create index if not exists memories_user_idx on memories (user_id);

alter table memories enable row level security;
create policy "own_memories" on memories
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Nearest memories by cosine distance, scoped to the caller. SECURITY INVOKER
-- (the default) means RLS still applies, but we also filter on user_id explicitly
-- so the ANN ordering never even considers other users' rows.
create or replace function match_memories(query_embedding vector(384), match_count int default 15)
returns table (id bigint, text text, summary text, category text, source text, created_at bigint, distance float)
language sql stable as $$
  select m.id, m.text, m.summary, m.category, m.source, m.created_at,
         (m.embedding <=> query_embedding) as distance
  from memories m
  where m.embedding is not null
    and m.user_id = auth.uid()
  order by m.embedding <=> query_embedding
  limit match_count;
$$;

-- ───────────────────────── Per-user settings ─────────────────────────
create table if not exists user_settings (
  user_id uuid primary key default auth.uid() references auth.users (id) on delete cascade,
  about_you text default '',
  custom_instructions text default '',
  memory_enabled boolean default true,
  updated_at bigint default 0
);

alter table user_settings enable row level security;
create policy "own_settings" on user_settings
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ───────────────────────── Shared chat snapshots ─────────────────────────
-- The slug `id` is an unguessable access token. Reads are PUBLIC (anyone with the
-- link, signed in or not) but only the owner can create or revoke a share.
create table if not exists shared_chats (
  id text primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  title text default 'Shared chat',
  messages jsonb not null default '[]'::jsonb,
  created_at bigint not null default 0
);

alter table shared_chats enable row level security;
create policy "public_read_shared" on shared_chats for select using (true);
create policy "owner_insert_shared" on shared_chats for insert with check (auth.uid() = user_id);
create policy "owner_delete_shared" on shared_chats for delete using (auth.uid() = user_id);

-- ───────────────────────── Subscriptions (Phase 2 — Stripe) ─────────────────────────
-- Placeholder for the $5/mo Pro tier. Written by the Stripe webhook (service role),
-- read by the user to know their plan. `plan` is 'free' | 'pro'.
create table if not exists subscriptions (
  user_id uuid primary key references auth.users (id) on delete cascade,
  plan text not null default 'free',
  status text default 'inactive',
  stripe_customer_id text,
  current_period_end bigint,
  updated_at bigint default 0
);

alter table subscriptions enable row level security;
create policy "own_subscription_read" on subscriptions for select using (auth.uid() = user_id);

-- ───────────────────────── Shared-quota usage tracking ─────────────────────────
-- The chat backend runs on ONE shared Ollama Cloud key across every visitor (GPU-time
-- billed, not request-count billed, with no API to check remaining quota — only a
-- dashboard + a 90%-usage email). A handful of heavy users can exhaust the whole
-- account for everyone. This tracks estimated generation-TIME (not message count —
-- a one-word reply and a 3000-word essay cost wildly different GPU-seconds) per
-- identity per day, plus a running whole-app total, so api/chat.js can refuse new
-- requests once either a per-identity or the shared global daily budget is spent.
--
-- No client access at all (no policies = fully locked down under RLS) — only the
-- server's service-role key touches these, via the record_usage() RPC below.
create table if not exists usage_ledger (
  identity text not null,
  day date not null,
  seconds numeric not null default 0,
  updated_at bigint not null default 0,
  primary key (identity, day)
);
alter table usage_ledger enable row level security;

create table if not exists global_usage (
  day date primary key,
  seconds numeric not null default 0,
  updated_at bigint not null default 0
);
alter table global_usage enable row level security;

-- Atomically adds p_seconds to both today's per-identity row and today's global row.
-- SECURITY DEFINER so it can write despite RLS locking the tables to zero client
-- policies — only reachable via the service-role key from api/chat.js, never the anon key.
create or replace function record_usage(p_identity text, p_seconds numeric)
returns void
language sql
security definer
set search_path = public
as $$
  insert into usage_ledger (identity, day, seconds, updated_at)
  values (p_identity, current_date, p_seconds, extract(epoch from now()) * 1000)
  on conflict (identity, day) do update
    set seconds = usage_ledger.seconds + excluded.seconds,
        updated_at = excluded.updated_at;

  insert into global_usage (day, seconds, updated_at)
  values (current_date, p_seconds, extract(epoch from now()) * 1000)
  on conflict (day) do update
    set seconds = global_usage.seconds + excluded.seconds,
        updated_at = excluded.updated_at;
$$;
